// <auto-generated />
namespace HotelApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FeedReservationStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeedReservationStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201812111328186_FeedReservationStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
